EA-198: Add support for configuring Mother Child relationships within…
openmrs/openmrs-module-emrapi pull request #237
Opened 2024-08-05 20:18 UTC by mogoodrich

… the EMR API module

2024-08-05 20:23 UTC, mogoodrich reviewed
I left this in draft format because the omod REST endpoint stuff still needs to be added but I wanted to put this out for review sooner rather than later, especially to get feedback on the name of the new service and overall structure, see my comments.
@cioan  @mseaton  @chibongho  flagging you all for review.

2024-08-05 20:23 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/emrapi/maternal/MaternalService.java
> +public interface MaternalService extends OpenmrsService {
Better ideas for a name of this? MaternityService? MaternalCareService?  Loop it into another service in EMR API (it doesn't really seem like an ADT method?)

(Note that there will like be a getMotherForNewborn()) service method as well.

2024-08-05 20:23 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/emrapi/maternal/Newborn.java
> +    private Visit newbornVisit;
We can evolve what this object should contain... it likely needs to contain admission information, but I haven't checked out the latest InpatientAdmission / InpatientRequest data structure and I wanted to see how that was evolving before digging too deep into this.

2024-08-05 21:39 UTC, mseaton commented on api/src/main/java/org/openmrs/module/emrapi/maternal/MaternalService.java
> +public interface MaternalService extends OpenmrsService {
You might just be able to slot this into the AdtService, since you are generally dealing with admitted patients here.  It would simplify the commit.  Otherwise, could potentially add to EmrPatientService.  Or, start some new, more generic service that we can add to when needed.

2024-08-05 21:39 UTC, mseaton commented on api/src/main/java/org/openmrs/module/emrapi/EmrApiConstants.java
> +    public static final String METADATA_MAPPING_MOTHER_CHILD_RELATIONSHIP_TYPE = "emrapi.motherChildRelationshipType";
Do you think we need to support A/B vs. B/A variations?

2024-08-05 21:39 UTC, mseaton commented on api/src/main/java/org/openmrs/module/emrapi/maternal/MaternalServiceImpl.java
> +    public List<Newborn> getNewbornsByMother(Patient mother, Location visitLocation) {
I'm a little worried about the efficiency of this.  I agree we want to support being able to getNewborns for a single mother, but we may need the overall method to be more efficient to operate in bulk in some way (eg. take in a List of mother patient ids and get back a Map<Mother, List<Baby>> or something.

2024-08-05 21:39 UTC, mseaton commented on api/src/main/java/org/openmrs/module/emrapi/maternal/MaternalServiceImpl.java
> +        parameters.put("visitLocation", visitLocation);
What is the purpose of the visitLocation parameter here?  If "mother" is required, are you saying "but don't return any babies for the mother if the visitLocation doesn't match"?  No, you should already have filtered by visitLocation to get the valid mothers.

2024-08-05 21:39 UTC, mseaton commented on api/src/main/resources/hql/newborns_by_mother.hql
> +    Visit as babyVisit
It would be more consistent with the other hql I recently added to connect the tables via joins rather than where criteria.

2024-08-05 21:39 UTC, mseaton commented on api/src/main/resources/hql/newborns_by_mother.hql
> +    and motherChildRelationship.personB = baby
Per my comment above, do we need to support the inverse here?

2024-08-05 21:39 UTC, mseaton commented on api/src/main/resources/hql/newborns_by_mother.hql
> +    and day(baby.birthdate) >= day(motherVisit.startDatetime)
are year/month/day like this more efficient than just casting to date? `and baby.birthdate >= date(motherVisit.startDatetime)`

2024-08-05 21:39 UTC, mseaton commented on api/src/main/resources/hql/newborns_by_mother.hql
> +    and (:visitLocation is null or (motherVisit.location = :visitLocation and babyVisit.location = :visitLocation))
I really don't see us ever limiting by visitLocation.  Even in the existing adt queries, I don't think we really have that use case...

2024-08-05 22:18 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/emrapi/EmrApiConstants.java
> +    public static final String METADATA_MAPPING_MOTHER_CHILD_RELATIONSHIP_TYPE = "emrapi.motherChildRelationshipType";
No.  I mean, at least not yet.  I think it's fair to say "to use the newborn functionality you will need to have a "mother-child" relationship type, where a_is_to_b=Mother and b_is_to_a=Child (which I think is implied in the name "mother-child).  If we discover that there's an existing implementation with a "Child-Mother relationship type" that wants to use this functionality we can consider supporting the B/A variation.  But I think by supporting both off the bat we are potentially encouraging/enabled implementations to not standardize.

2024-08-05 22:18 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/emrapi/maternal/MaternalService.java
> +public interface MaternalService extends OpenmrsService {
I'm fine with putting this in ADTService, or moving it to the EmtrPatientService.    I don't really want to create a new generic service because we will just be guessing on a good generic name and I suspect we will regret whatever name we choose down the road.

2024-08-05 22:18 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/emrapi/maternal/MaternalServiceImpl.java
> +    public List<Newborn> getNewbornsByMother(Patient mother, Location visitLocation) {
Fair.  It's likely easy enough to support multiple patients.  Though I'm a little worried about how we'd hand this on the client side.  ie, it's nice to be able to separate the concerns of how to fetch the relevant data needed to display the patient card from fetching the list of the patients on the ward.

2024-08-05 22:18 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/emrapi/maternal/MaternalServiceImpl.java
> +        parameters.put("visitLocation", visitLocation);
Good point.  I'll sleep on this in case I'm forgetting something, but that does seem to make sense.

2024-08-05 22:18 UTC, mogoodrich commented on api/src/main/resources/hql/newborns_by_mother.hql
> +    and day(baby.birthdate) >= day(motherVisit.startDatetime)
Would have much preferred to use "date" but as far as I could tell it wasn't available in HQL

2024-08-06 11:45 UTC, mseaton commented on api/src/main/java/org/openmrs/module/emrapi/EmrApiConstants.java
> +    public static final String METADATA_MAPPING_MOTHER_CHILD_RELATIONSHIP_TYPE = "emrapi.motherChildRelationshipType";
Makes sense, agreed.

2024-08-06 11:45 UTC, mseaton commented on api/src/main/java/org/openmrs/module/emrapi/maternal/MaternalService.java
> +public interface MaternalService extends OpenmrsService {
OK, defer to you.

2024-08-06 11:45 UTC, mseaton commented on api/src/main/java/org/openmrs/module/emrapi/maternal/MaternalServiceImpl.java
> +    public List<Newborn> getNewbornsByMother(Patient mother, Location visitLocation) {
Yeah, agree, just wanted to flag it.

2024-08-06 11:45 UTC, mseaton commented on api/src/main/resources/hql/newborns_by_mother.hql
> +    and day(baby.birthdate) >= day(motherVisit.startDatetime)
Oh right.  Hql.

2024-08-06 13:23 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/emrapi/maternal/MaternalServiceImpl.java
> +    public List<Newborn> getNewbornsByMother(Patient mother, Location visitLocation) {
I think it's easy enough to support 1 to n, I will likely add that.

2024-08-06 22:21 UTC, mogoodrich commented
Moving this out of draft state even though it still doesn't have the code to expose these service methods as REST endpoints, will likely work on that as a separate PR.

I have made changes and added a baby-for-mother inverse service method and added some comments, flagging @mseaton  for re-review.

2024-08-06 22:21 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/emrapi/maternal/MaternalService.java
> +public interface MaternalService extends OpenmrsService {
So, I started to move this into AdtService, but I like the ideal of smaller, targeted services rather than bloat, so I'd prefer to keep this separate for "Maternal" functionality, especially now that we have two methods.

2024-08-06 22:21 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/emrapi/maternal/MaternalService.java
> +    public List<Mother> getMothersByNewborn(List<Patient> newborns);
Added this since the last commit.

One thing it *doesn't* do is confirm that the newborns are actually "newborns", so the client side will have to handle this; easy enough to support this if we want to, but it seemed weird to have the method potentially one of the inputs.  Practically, this would only make a different if there were a mother and a child in the same hospital and the child is *not*  a newborn... the mother would still show up on the child's card, which certainly isn't the end of the world.

I also considered a single method that, given a patient set, would use a single query to fetch both NewbornsByMother and MothersByNewborn.  This seemed like it would be straightfoward to write and would save us a REST call and a query, but it seemed like things would be getting too confusing for the consumer to understand.

2024-08-06 22:21 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/emrapi/maternal/MaternalServiceImpl.java
> +        // now fetch all the admissions for newborns in the result set
We need the inpatient admission for the newborn so we can should their current location.  I followed a similar pattern to what @mseaton  for fetching all inpatient requests associated with inpatient admission.

2024-08-06 22:21 UTC, mogoodrich commented on api/src/main/resources/hql/mothers_by_newborn.hql
> +  and babyVisit.location = motherVisit.location
I added this restriction (mother and baby visits must be at the same location). This might be problematic for implementations that collect visit location at a greater level of granularity than at the facility level, but it seemed like something we should do in preparation for a more cloud-based model where there are multiple facilities in the same database.

2024-08-06 22:40 UTC, mogoodrich commented on api/src/main/resources/hql/newborns_by_mother.hql
> +    inner join motherChildRelationship.personB as baby
And, oh, I converted this somewhat to inner joins, but needed help on how do this when can't just chain the joins... ie relationship links to person/patient, but then visit links to patient not the other way around... hope that made some sense and I'm not just missing something obvious.  :)

2024-08-06 23:44 UTC, mseaton requested changes

2024-08-06 23:44 UTC, mseaton commented on api/src/main/java/org/openmrs/module/emrapi/maternal/MaternalService.java
> +    public List<Newborn> getNewbornsByMother(List<Patient> mothers);
This is where I found a lot of value (and really like the pattern) of using `SearchCriteria`.  So if we continue with these methods (and I have other feedback that may supercede this), it might be preferable to do something like `getNewborns(NewbornSearchCriteria)`, and then one of the properties of `NewbornSearchCriteria` might be which mothers to search on, but other use cases can emerge to get Newborns by something other than their mothers (or in addition).

Also, it is potentially more expensive to take in a List<Patient> here, if you need to look up a bunch of patient by id or uuid before passing them in.

2024-08-06 23:44 UTC, mseaton commented on api/src/main/java/org/openmrs/module/emrapi/maternal/MaternalService.java
> +    public List<Mother> getMothersByNewborn(List<Patient> newborns);
Same comment as above.  `getMothers(MotherSearchCriteria)`.  But see my other comments below also.

2024-08-06 23:44 UTC, mseaton commented on api/src/main/java/org/openmrs/module/emrapi/maternal/MaternalServiceImpl.java
> +        // now fetch all the admissions for newborns in the result set
So Mother and Newborn are inherently _admitted_ patients who just delivered / were born within the facility, but I'm not sure that is necessarily obvious to consumers of a MaternalService that are getting mothers and babies.

I think I might just move everything into the `adt` domain and `AdtService` if we are dealing with ADT things - in this case, these are really more specific instances of InpatientAdmission (eg. subclass or wrapper class).

I think it would be more intuitive if `Mother` -> `MaternalAdmission` and `Newborn` -> `NewbornAdmission`, both of which `extend InpatientAdmission`.  

Then we add methods to AdtService for `getMaternalAdmissions(MaternalAdmissionSearchCriteria)` and `getNewbornAdmissions(NewbornAdmissionSearchCriteria)`

```
  MaternalAdmission extends InpatientAdmission (
    private List<NewbornAdmission> newbornAdmissions;
  )
```

```
  NewbornAdmission extends InpatientAdmission (
    private List<MaternalAdmission> maternalAdmission;
  )
```

Then the ward app can just get these directly, without making any additional queries...

2024-08-06 23:44 UTC, mseaton commented on api/src/main/java/org/openmrs/module/emrapi/maternal/Mother.java
> +    private InpatientAdmission motherAdmission;
See comment above where we could make `Mother` -> `MaternalAdmission`

2024-08-06 23:44 UTC, mseaton commented on api/src/main/java/org/openmrs/module/emrapi/maternal/Newborn.java
> +    private InpatientAdmission newbornAdmission;
See comment above where we could make `Newborn` -> `NewbornAdmission`

2024-08-06 23:44 UTC, mseaton commented on api/src/main/resources/hql/mothers_by_newborn.hql
> +  and babyVisit.location = motherVisit.location
I feel like this is more likely to cause data to be excluded that shouldn't be, than include too much data, at least in the short term.  We can always add this restriction in, but I'd be a little wary about it.  I don't think there are a lot of use cases where we want to exclude babies from mothers who were born after the mothers visit start date, because they are in different facilities in a federated system.  Seems unlikely.

2024-08-06 23:44 UTC, mseaton commented on api/src/main/resources/hql/mothers_by_newborn.hql
> +  and babyVisit.patient = baby and babyVisit.stopDatetime is null
Maybe this is going over the same ground as my other comments, but I don't love all of these restrictions here in a "generic" mothers by newborn method.  If someone were to see a getMothersByNewborn method, passing in a Newborn, and got null back for the mother because the mother no longer had an active visit, that would seem...unexpected.  Another reason why I like being more explicit with our naming around XxxAdmission

2024-08-06 23:44 UTC, mseaton commented on api/src/main/resources/hql/newborns_by_mother.hql
> +    and babyVisit.patient = baby and babyVisit.stopDatetime is null
Same comment as before.  Consumers will wonder why no babies are returned for a mother just because they no longer have an active visit.  That seems more like a front-end concern than the concern of a back-end service method, unless we make this much more explicitly specific.

2024-08-07 13:44 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/emrapi/maternal/MaternalService.java
> +    public List<Newborn> getNewbornsByMother(List<Patient> mothers);
Passing in uuids/ids likely makes sense here, good point...

2024-08-07 21:25 UTC, mogoodrich reviewed
Okay, ready for re-review @mseaton ... I still need to add the REST endpoint and add new javadocs for thee new service but this updated commit now:

* Uses search criteria objects for Mother and Child searches, enabling configuring whether to limit to patients with actvive visits
* Uses a list of patient uuids for the search instead of patient objects
* Standardizing naming convention on child (instead of "baby" and "newborn")

2024-08-08 13:11 UTC, mseaton commented on api/src/main/java/org/openmrs/module/emrapi/maternal/Child.java
> +    private Patient mother;
Thoughts about making this to be `private Mother mother;`?

2024-08-08 13:11 UTC, mseaton commented on api/src/main/java/org/openmrs/module/emrapi/maternal/Mother.java
> +    private Patient child;
Thoughts about making this `private Child child;`?

2024-08-08 18:47 UTC, mogoodrich reviewed
@mseaton  I made most, but not all of the suggested changes, see my comments and updated PR.

Going to go ahead and merge this in.

2024-08-08 18:47 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/emrapi/maternal/Child.java
> +    private Patient mother;
I'd rather keep the REST response as simple as possible.  You mean have:

```
public class Mother {
    private Patient mother;
    private Child child;
    private InpatientAdmission motherAdmission;
}


public class Child {
    private Patient child;
    private Mother mother;
    private InpatientAdmission childAdmission;
}
```

Then on a child you've have to child.mother.mother to get the mother?

2024-08-08 18:47 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/emrapi/maternal/Mother.java
> +    private Patient child;
See above

2024-08-08 18:47 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/emrapi/maternal/MotherSearchCriteria.java
> +@Data
Done

2024-08-08 18:47 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/emrapi/maternal/MaternalService.java
> +    public List<Child> getChildrenByMother(ChildSearchCriteria criteria);
So I changed this to getChildren, but (almost) back to the original, making the mothers plural: "getChildrenByMothers".  I *did* remove making setting mother uuids mandatroy, but I think the name should stay, reflecting the case that this returns child-mother pairs, (and, in particular, would return two rows for single child if they had two or mother mothers... admittedly, not a standard case, but certainly a standard case for the inverse, getMothersByChild).

2024-08-08 18:47 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/emrapi/maternal/MaternalService.java
> +    public List<Mother> getMothersByChild(MotherSearchCriteria criteria);
See above (and I did remove making setting child uuids mandatory)

2024-08-08 18:47 UTC, mogoodrich commented on api/src/main/resources/hql/mothers_by_child.hql
> +
Done.  And now both support childBornDuringMothersActiveVisit

2024-08-08 18:49 UTC, merged

2024-08-08 19:44 UTC, mseaton commented on api/src/main/java/org/openmrs/module/emrapi/maternal/ChildrenByMothersSearchCriteria.java
> +    @Accessors(fluent = true)  private boolean requireChildBornDuringMothersActiveVisit = false;  // restrict to children who were born during their mother's active visit
What is this `fluent = true`?  Don't we want these to act and behave like standard Javabean properties?

2024-08-08 19:48 UTC, mseaton commented on api/src/main/java/org/openmrs/module/emrapi/maternal/Child.java
> +    private Patient mother;
Hmm.  I think given what you have in place it would make sense to just have one object:

```
public class MotherAndChild {
    private Patient mother;
    private Child child;
    private InpatientAdmission motherAdmission;
    private InpatientAdmission childAdmission;
}
```

And then one service method to `getMothersAndChildren(MothersAndChildrenSearchCriteria)` that returns a List of these.

That list would contain all children of interest if you pass it a set of child uuids, and would contain all mothers of interest if you pass it was set of mother uuids, and everyone of interest if you just pass it criteria about the visit constraints expected...

2024-08-08 19:49 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/emrapi/maternal/ChildrenByMothersSearchCriteria.java
> +    @Accessors(fluent = true)  private boolean requireChildBornDuringMothersActiveVisit = false;  // restrict to children who were born during their mother's active visit
It makes the getter/setter "requireMotherHasActiveVisit" instead of "isRequireMotherHasActiveVisit"... "is" is the default for "boolean" types and that read horribly. https://projectlombok.org/features/experimental/Accessors

2024-08-08 19:50 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/emrapi/maternal/ChildrenByMothersSearchCriteria.java
> +    @Accessors(fluent = true)  private boolean requireChildBornDuringMothersActiveVisit = false;  // restrict to children who were born during their mother's active visit
No idea why it's called fluent. :)

2024-08-08 19:50 UTC, mseaton commented on api/src/main/java/org/openmrs/module/emrapi/maternal/MaternalService.java
> +    List<Mother> getMothersByChildren(MothersByChildrenSearchCriteria criteria);
Regarding these method names, see my suggestion above.  These aren't "ByMothers" or "ByChildren" at all.  They are really lists of MotherAndChild objects.  They aren't "by" anything.

2024-08-08 19:51 UTC, mseaton commented on api/src/main/java/org/openmrs/module/emrapi/maternal/Mother.java
> +    private Patient child;
See above again.

2024-08-08 19:51 UTC, mseaton commented on api/src/main/java/org/openmrs/module/emrapi/maternal/MothersByChildrenSearchCriteria.java
> +    @Accessors(fluent = true)  private boolean requireChildBornDuringMothersActiveVisit = false;  // restrict to mothers who had a child born during their active visit
Ditto

2024-08-08 19:52 UTC, ibacher commented on api/src/main/resources/hql/mother_child.hql
> +        inner join motherChildRelationship.personB as child
Are relationships always uni-directional like this, i.e., with a fixed A/B? (The flexibility around this is one of the things I've always disliked about relationships).

2024-08-08 19:53 UTC, mseaton commented on api/src/main/java/org/openmrs/module/emrapi/maternal/ChildrenByMothersSearchCriteria.java
> +    @Accessors(fluent = true)  private boolean requireChildBornDuringMothersActiveVisit = false;  // restrict to children who were born during their mother's active visit
I understand what it does, but nothing else that works with JavaBean objects will be able to deal with this.  We should make it standard, even if it reads poorly, or try to change the variable name so it reads better with an "is" or "get" prefix.

2024-08-08 19:59 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/emrapi/maternal/Child.java
> +    private Patient mother;
Yeah, I was thinking of that, though I thought there was a reason it wasn't going to work, will check again.

2024-08-08 21:04 UTC, mogoodrich commented on api/src/main/resources/hql/mother_child.hql
> +        inner join motherChildRelationship.personB as child
They are flexible, but we are saying this is based around have a standardized uni-directional "Mother to Child" relationship type

2024-08-08 21:33 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/emrapi/maternal/ChildrenByMothersSearchCriteria.java
> +    @Accessors(fluent = true)  private boolean requireChildBornDuringMothersActiveVisit = false;  // restrict to children who were born during their mother's active visit
ah... let's just stick with the ugly name then, will change.