Implement an API for Fetching Visits with Notes and Diagnosis
openmrs/openmrs-module-emrapi pull request #250
Opened 2024-10-24 13:57 UTC by jayasanka-sack

2024-10-24 14:33 UTC, mogoodrich commented
@jayasanka-sack  can you write up an EMR-API ticket in Jira describing the use cases on what this PR is intended to accomplish?  thanks, fyi @mseaton

2024-10-24 14:39 UTC, jayasanka-sack commented
Hey @mogoodrich The ticket is: https://openmrs.atlassian.net/browse/EA-207

But this PR is still under WIP. I'll let you know when it is ready for review.

2024-12-02 17:05 UTC, mogoodrich requested changes
Thanks @jayasanka-sack !  Good to see we are adding methods to the EMR API to support performant queries in O3.

See my comments and let me know if you have questions... also, can you add a link to this PR to the ticket?  

Also, it looks like this is really just returning "Visits With Diagnoses" (not "Visits with Notes and Diagnsoes")... which is fine, just wanted to confirm it is what you were looking for.

also fyi @mseaton

2024-12-02 17:08 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/emrapi/db/VisitDAO.java
> +public interface VisitDAO {
I think we may want to call with EmrApiVisitDAO to distinguish it from the Core one?  Thoughts @mseaton  @ibacher ?

2024-12-02 17:08 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/emrapi/visit/VisitWithDiagnosesService.java
> +public interface VisitWithDiagnosesService {
Maybe call this EmrApiVisitService (and we can use it for other Visit-related services we add to EMR API)?  Thoughts @mseaton  @ibacher ?

2024-12-02 17:21 UTC, ibacher commented on api/src/main/java/org/openmrs/module/emrapi/db/VisitDAO.java
> +public interface VisitDAO {
Agreed.

2024-12-02 17:21 UTC, ibacher commented on api/src/main/java/org/openmrs/module/emrapi/visit/VisitWithDiagnosesService.java
> +public interface VisitWithDiagnosesService {
Yeah, that's a very good idea!

2024-12-02 17:31 UTC, mseaton requested changes

2024-12-02 17:31 UTC, mseaton commented on api/src/main/java/org/openmrs/module/emrapi/db/HibernateVisitDAO.java
> +@Repository
I have never seen this annotation actually used in this module before.  Are we sure this works?  I'd prefer we stick with existing conventions within the module for wiring things up, and then do a change to everything if we want to update to a new mechanism.

2024-12-02 17:31 UTC, mseaton commented on api/src/main/java/org/openmrs/module/emrapi/db/HibernateVisitDAO.java
> +    @Autowired
Usually we do not autowire into a DAO AFAIK, but we use xml.  There are definitely performance issues to using Autowired in services, and I'm not sure if those carry over to DAOs.

2024-12-02 17:31 UTC, mseaton commented on api/src/main/java/org/openmrs/module/emrapi/db/VisitDAO.java
> +public interface VisitDAO {
Do we really need an entirely new DAO class we have to wire up and maintain?  Can't we just move to having one DAO for the entire module?

2024-12-02 17:31 UTC, mseaton commented on api/src/main/java/org/openmrs/module/emrapi/visit/VisitWithDiagnosesService.java
> +public interface VisitWithDiagnosesService {
Yes!  Let's move towards having fewer distinct DAOs and Services in this module

2024-12-02 17:31 UTC, mseaton commented on omod/pom.xml
> +        </dependency>
We either should choose to use Junit 4 or Junit 5 for the entire module.  I don't want us to have to try to support both in one module, there are too many annoying gotchas.

2024-12-02 17:31 UTC, mseaton commented on omod/src/main/java/org/openmrs/module/emrapi/web/controller/VisitController.java
> +    public ResponseEntity<?> getVisitsByPatientId(
And the endpoint should not be `/.../visit`, but should reflect that it is a `/.../visitWithDiagnoses` or something

2024-12-02 18:38 UTC, mogoodrich commented on omod/pom.xml
> +        </dependency>
Yes, if it's problematic to support both JUnit 4 and JUnit 5 in a single module, let's just go with JUnit 4 until we feel motivated to update all the tests.

2024-12-09 05:45 UTC, jayasanka-sack commented
Appreciate the feedback @mogoodrich and @mseaton! I’ll take a look and follow up with you.

2024-12-09 09:12 UTC, jayasanka-sack commented on omod/src/main/java/org/openmrs/module/emrapi/web/controller/VisitController.java
> +            @PathVariable String patientUuid) {
I’m guessing it needs to be called with ?patient={uuid} but it’s returning a 500 with no body, and I’m having a hard time debugging it. Can you point me to where the conversion happens? I noticed a couple of other endpoints which use the same, but I couldn’t find any tests for them or any part of the frontend that calls them.

2024-12-09 10:56 UTC, jayasanka-sack commented on api/src/main/java/org/openmrs/module/emrapi/db/HibernateVisitDAO.java
> +        String visitNoteEncounterTypeUuid = "d7151f82-c1f3-4152-a605-2f9ea7414a79";
We’re including this to get only note encounters with the visit, but we also need visits that don’t have encounters. I’ve updated the query with a left join and modified the test accordingly.

2024-12-09 11:14 UTC, jayasanka-sack commented
I still have to address some comments. I'll get them fixed and get back to you.

2024-12-09 19:45 UTC, ibacher commented on omod/src/main/java/org/openmrs/module/emrapi/web/controller/VisitController.java
> +            @PathVariable String patientUuid) {
Unfortunately, it's part of the [UI framework](https://github.com/openmrs/openmrs-module-uiframework/blob/1f88e1892b9becddf44c9f6666e73947bcb0aad9/api/src/main/java/org/openmrs/ui/framework/converter/StringToPatientConverter.java#L8), which is almost certainly not the right place for it. I think you could also do `@PathVariable("patientUuid") Patient patient` with the right converter.

2024-12-09 21:19 UTC, mogoodrich reviewed
Sorry, juts realized I had a couple "pending" comments that I never submitted.

2024-12-16 16:46 UTC, jayasanka-sack commented on api/src/test/resources/metadata/pastVisitSetup.xml
> +<?xml version='1.0' encoding='UTF-8'?>
Both files are used in tests in both modules.

2024-12-16 16:47 UTC, ibacher commented on omod/src/main/java/org/openmrs/module/emrapi/web/controller/VisitController.java
> +            @PathVariable String patientUuid) {
Did you try adding the UIFramework module?

2024-12-16 16:50 UTC, ibacher commented on omod/src/main/java/org/openmrs/module/emrapi/web/controller/VisitController.java
> +            @PathVariable String patientUuid) {
@mogoodrich @mseaton Do you think there's any objection to migrating the various converters out of the UI framework and into somewhere else? (My two initial thoughts are either: add them to EMR API or add them to the REST module; they don't _quite_ fit in the REST module, but it's actually a helpful thing to have).

2024-12-16 17:03 UTC, mseaton commented on omod/src/main/java/org/openmrs/module/emrapi/web/controller/VisitController.java
> +            @PathVariable String patientUuid) {
No real objection, but also no need to get bogged down on this.  Just accept a String parameter (which could be a uuid or primary key id), and convert it to a patient in the controller...

2024-12-16 19:02 UTC, mogoodrich commented on omod/src/main/java/org/openmrs/module/emrapi/web/controller/VisitController.java
> +            @PathVariable String patientUuid) {
Huh, so things like the ActiveVisitController have been dependent on UI Framework module all along, we just never realized it because we've generally always been running EMR API and UI Framework together?

No strong objection to move them... I think I'd have slight preference for moving them to EMR API instead of REST Web Services, but haven't thought it all through.  We also could potentially add them to Core? (Though of course the adoption time would be slower that way).

2024-12-17 15:31 UTC, mogoodrich commented on omod/src/main/java/org/openmrs/module/emrapi/web/controller/VisitController.java
> +            @PathVariable String patientUuid) {
Also, it looks like REST WS may have it's own converters, fwiw...

2024-12-17 16:08 UTC, ibacher commented on omod/src/main/java/org/openmrs/module/emrapi/web/controller/VisitController.java
> +            @PathVariable String patientUuid) {
REST has [it's own Converter concept](https://github.com/openmrs/openmrs-module-webservices.rest/blob/f3d8915f3990c9e65e49e0f33495b497b6d2ac81/omod-common/src/main/java/org/openmrs/module/webservices/rest/web/resource/api/Converter.java#L20), but it's actually distinct from the Spring converters, I think.

2024-12-17 16:09 UTC, ibacher commented on omod/src/main/java/org/openmrs/module/emrapi/web/controller/VisitController.java
> +            @PathVariable String patientUuid) {
> We also could potentially add them to Core? (Though of course the adoption time would be slower that way)

Yeah, I'd like to migrate them to core eventually, but we just released 2.7.0, so it's not the _best_ time to do that. Easy enough to add to a module and then add an `@OpenmrsProfile` to exclude them once they're available in core.

2024-12-17 18:00 UTC, mogoodrich reviewed
Thanks @jayasanka-sack , getting close!  See my updated thoughts/questions.

2024-12-17 18:00 UTC, mogoodrich commented on api/src/test/resources/metadata/pastVisitSetup.xml
> +<?xml version='1.0' encoding='UTF-8'?>
What is the distinction between them?

2024-12-18 12:38 UTC, jayasanka-sack commented on api/src/main/java/org/openmrs/module/emrapi/db/EmrApiDAOImpl.java
> +              "LEFT JOIN FETCH v.encounters enc " +
Yes, you’re right! 

I used the FETCH syntax to load encounters eagerly instead of lazily.

2024-12-18 16:39 UTC, ibacher commented on api/src/test/resources/metadata/pastVisitSetup.xml
> +<?xml version='1.0' encoding='UTF-8'?>
Yeah the organization is a little weird. It looks like there may have been some convention for all the metadata to go into a file like this and the data into a file like the other one, but both of them mix data and metadata, so it's confusing why we need the two.

2025-01-21 19:04 UTC, ibacher reviewed
Thanks @jayasanka-sack! A few comments and suggestions.

2025-01-21 19:57 UTC, mogoodrich commented
Sorry @jayasanka-sack  I haven't been following this... is this ready for re-review?

2025-01-21 20:04 UTC, ibacher commented
@mogoodrich Yes, it is.

2025-01-21 20:14 UTC, mseaton commented on omod/src/main/resources/moduleApplicationContext.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This is unnecessary.  Just use Autowired on the emrApiVisitService property on the controller.  It is already an annotated controller, so does not need to be wired in like this, does it?

2025-01-21 21:16 UTC, mogoodrich requested changes
I have some comments, but I have a bigger question about the design, apologies for not raising it earlier.

If I'm understanding, the REST endpoint returns something in the format:

```
[
  {
      "visit": ...
      "diagnoses": ...
  },
  {
      "visit": ...
      "diagnoses": ...
  }
]
```

... but via the magic of Hibernate someone the only encounters on those visits objects are ones that are visit notes?  Am I understanding that right and are we sure that works?  Beyond that, I think it's confusing for the consumer because the assumption is that the visit contains *all* the encounters for patient.  I'd prefer to return something in this format:

```
[
  {
      "visit": ...
      "diagnoses": ...
      "visitNotes": ....
  },
  {
      "visit": ...
      "diagnoses": ...
      "visitNotes": ....
  }
]
```

Am I understanding this correctly? Apologies for not flagging this sooner.  Also fyi @mseaton  @ibacher

2025-01-21 21:16 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/emrapi/db/EmrApiDAOImpl.java
> +   public List<VisitWithDiagnoses> getVisitsWithNotesAndDiagnosesByPatient(Patient patient, int startIndex, int limit) {
@ibacher  are you referring to the "VisitWithDiagnoses" type (and the fact that "Notes" is missing?)  This does seem kind of weird, though, the object is literally just a "VisitWithDiagnoses" object, but (if I understand this correctly) when we populate this Visit in the DAO we *only* populate it with the Visit Note encounters associated with it, not all the encounters associated with it.

2025-01-21 21:16 UTC, mogoodrich commented on api/src/main/java/org/openmrs/module/emrapi/db/EmrApiDAOImpl.java
> +              "LEFT JOIN FETCH v.encounters enc " +
fyi @mseaton  @ibacher

2025-01-21 21:16 UTC, mogoodrich commented on api/src/test/java/org/openmrs/module/emrapi/db/EmrApiDaoTest.java
> +            assert encounter.getEncounterType().getUuid().equals(visitNoteEncounterTypeUuid);
Following up on my comment from above, I'm a little confused by this, as it looks like in the test data below this visit has two encounters but one is *not* a visit note?

2025-01-21 21:23 UTC, ibacher commented
Oh! I see I missed that we're fetching the encounters with the visit note type.!

2025-01-22 13:25 UTC, jayasanka-sack commented
Thanks a bunch for your feedback, @ibacher, @mogoodrich, @mseaton! I’ll take a look at these comments and get back to you soon.

2025-02-05 13:22 UTC, jayasanka-sack commented on api/src/main/java/org/openmrs/module/emrapi/db/EmrApiDAOImpl.java
> +              "ORDER BY v.startDatetime DESC";
Yeah, I removed the sorting from the stream as database level sorting is generally faster.

2025-02-05 13:24 UTC, jayasanka-sack commented on api/src/main/java/org/openmrs/module/emrapi/visit/EmrApiVisitServiceImpl.java
> +        Patient patient = patientService.getPatientByUuid(patientUuid);
Patient UUID is a path parameter, which cannot be empty. If it is empty, Spring will treat `//` as a different path and will not match it to the controller, resulting in a 404 Not Found error

2025-02-05 14:28 UTC, jayasanka-sack commented
@mogoodrich Your suggestion makes more sense since it prevents confusion where developers might think it includes all encounters. So I added the visitNote property to the `VisitWithDiagnosesAndNotes` class and removed encounters (which are basically visit notes) from visit objects by setting them to an empty hashmap. Is there a better way to completely remove the property from the payload?

2025-02-05 14:29 UTC, jayasanka-sack commented on api/src/main/java/org/openmrs/module/emrapi/visit/EmrApiVisitServiceImpl.java
> +            throw new ObjectNotFoundException("No patient found with uuid " + patientUuid, Patient.class.getName());
Done, and updated the controller to catch it and send a 400 code.

2025-02-05 14:33 UTC, jayasanka-sack commented on api/src/test/resources/metadata/pastVisitSetup.xml
> +<?xml version='1.0' encoding='UTF-8'?>
My bad! This is an extra file that wasn’t needed. By the way, about the XML file that was used in both modules’ tests, I ended up reusing the same one using the test jar.

2025-02-05 14:41 UTC, jayasanka-sack commented on api/src/test/java/org/openmrs/module/emrapi/db/EmrApiDaoTest.java
> +            assert encounter.getEncounterType().getUuid().equals(visitNoteEncounterTypeUuid);
Yeah, the test data includes other encounters too, but this check ensures that only visit encounters are returned. That said, it's slightly better now with the new property for visits.

2025-02-05 14:53 UTC, jayasanka-sack commented on api/src/test/java/org/openmrs/module/emrapi/db/EmrApiDaoTest.java
> +    public void shouldFetchVisitsWithNotesAndDiagnosesByPatientId() {
According to the my previous implementation, it won't delete other encounters as I didn't explicitly setEncounters later, so that it won't marked as a dirty object. So the encounters won't have an impact event if it is persisted.

However, after the change, now that I set encounters to an empty set later, hibernate will delete the encounters if the visits is re-saved. How about marking the transaction as a read only one? I think this depends on the answer to my question here: https://github.com/openmrs/openmrs-module-emrapi/pull/250#issuecomment-2637004502

2025-02-05 15:03 UTC, mogoodrich commented on api/src/test/java/org/openmrs/module/emrapi/db/EmrApiDaoTest.java
> +    public void shouldFetchVisitsWithNotesAndDiagnosesByPatientId() {
I still think it's better to return visitNotes as a separate field on the result rather than relying on this Hibernate magic to return a visit with only a subset of encounters. @mseaton  @ibacher @jayasanka-sack ?

2025-02-05 15:06 UTC, mogoodrich commented on api/src/test/java/org/openmrs/module/emrapi/db/EmrApiDaoTest.java
> +    public void shouldFetchVisitsWithNotesAndDiagnosesByPatientId() {
Oh sorry, just saw your other comment @jayasanka-sack let me comment on that...

2025-02-05 15:09 UTC, mogoodrich commented
> @mogoodrich Your suggestion makes more sense since it prevents confusion where developers might think it includes all encounters. So I added the visitNote property to the `VisitWithDiagnosesAndNotes` class and removed encounters (which are basically visit notes) from visit objects by setting them to an empty set. Is there a better way to completely remove the property from the payload?

At the end of the day, this new service method is for use for a new endpoint, correct? If you change that endpoint to only include a REF reference of the encounters, does that fix the performance problems without having to specifically *remove* the encounters property?

2025-02-10 13:39 UTC, jayasanka-sack commented
@mogoodrich yeah that would also work.  A solution would be:

1. Get visits without filtering encounters
2. Filter note encounters of each visits and include into the property visitNotes

Since visited are converted in default representation (unless specified), encounters will have in REF representation. And notes are converted in default representation too, since they'll converted manually. Using `FETCH` for loading encounters is still a good idea to avoid N+1 query problem.

However, my concern is that if we 100% do not need encounters for this use case, is it worth the extra work? It increases both time complexity (`O(k * n)`) and memory usage where:

- `k` = number of visits per request (constant due to pagination),
- `n` = number of encounters per visit (mostly ≤ 20 but still adds up over many requests).

This might be not noticeable, but when this is on a server the inefficiency scales with increasing traffic.

Perhaps this might not a big deal, but jus wanted to bring it up since the goal is to improve performance of visit fetching, let me know what you think. 

cc: @ibacher @mseaton

2025-02-10 13:58 UTC, jayasanka-sack commented
btw, it's worth noting that serialization process already has an O(k * n) complexity when converting notes. So it won’t reduce the total time complexity by more than half. But will reduces unnecessary data fetching and memory usage slightly.

2025-02-10 17:45 UTC, mogoodrich commented
Thanks @jayasanka-sack !  It feels like historically the it's been Hibernate and hydrating Hibernate-managed objects that cause the slowdown, so I was hoping that just having the REF representation of encounters would solve this.  But I can see if you have to fetch all the encounters and then filter them by encounter type that would likely hurt performance.

I'm okay with just removing the encounters from the visit property, but I would think then the visit should not have an "encounter" property at all (as opposed to an empty set, which would suggest that the visit has no encounters) but this might be tricky to do).  Thoughts @ibacher  @mseaton ?

2025-02-10 18:02 UTC, ibacher commented on api/src/main/java/org/openmrs/module/emrapi/visit/VisitWithDiagnosesAndNotes.java
> +    private Set<Encounter> visitNotes;
For visit notes, we don't even necessarily just need the _encounter_; it's just the individual notes obs withing them that really matter.

2025-02-18 13:32 UTC, jayasanka-sack commented on api/src/main/java/org/openmrs/module/emrapi/visit/VisitWithDiagnosesAndNotes.java
> +    private Set<Encounter> visitNotes;
Fixed it. Also, used a custom representation to filter out unnecessary data (plus to prevent additional queries)

2025-02-18 13:53 UTC, jayasanka-sack commented
Update: @ibacher and I had a discussion, and the outcome was to use a custom representation, so that we can eliminate encounters and other irrelevant properties, which also helps us to get rid of additional db queries.

Other changes:
- Fetch only Observation of each note encounters
- Updated queries to filter out voided records
- Update test cases to test voided data

2025-02-18 14:11 UTC, jayasanka-sack commented on api/src/main/java/org/openmrs/module/emrapi/visit/EmrApiVisitServiceImpl.java
> +        Patient patient = patientService.getPatientByUuid(patientUuid);
fixed with https://github.com/openmrs/openmrs-module-emrapi/pull/250/commits/3643d16203cc6ccd115a6e335e9968e89c545dc3

2025-02-18 14:11 UTC, jayasanka-sack commented on api/src/main/java/org/openmrs/module/emrapi/db/EmrApiDAOImpl.java
> +              "WHERE e.visit.id IN :visitIds";
Fixed with https://github.com/openmrs/openmrs-module-emrapi/pull/250/commits/3643d16203cc6ccd115a6e335e9968e89c545dc3

2025-02-18 14:11 UTC, jayasanka-sack commented on api/src/main/java/org/openmrs/module/emrapi/db/EmrApiDAOImpl.java
> +              "ORDER BY v.startDatetime DESC";
Fixed with https://github.com/openmrs/openmrs-module-emrapi/pull/250/commits/3643d16203cc6ccd115a6e335e9968e89c545dc3

2025-02-18 18:22 UTC, mogoodrich commented
> Update: @ibacher and I had a discussion, and the outcome was to use a custom representation, so that we can eliminate encounters and other irrelevant properties, which also helps us to get rid of additional db queries during the conversion.
> 
> Other changes:
> 
> * Fetch only Observation of each note encounters
> * Updated queries to filter out voided records
> * Update test cases to test voided data

Sounds good to me, thanks @jayasanka-sack !

2025-02-20 03:46 UTC, ibacher approved these changes

2025-02-20 03:46 UTC, ibacher commented on api/src/main/java/org/openmrs/module/emrapi/db/EmrApiDAOImpl.java
> +                 ArrayList<Obs> notes = visitIdToNotesMap.getOrDefault(visit.getId(), new ArrayList<>());
```suggestion
                 ArrayList<Obs> notes = visitIdToNotesMap.getOrDefault(visit.getId(), ArrayList::new);
```

2025-02-20 03:46 UTC, ibacher commented on omod/src/main/java/org/openmrs/module/emrapi/web/controller/VisitController.java
> +        }catch (APIException e) {
```suggestion
        } catch (APIException e) {
```

2025-02-20 03:46 UTC, ibacher commented on api/src/main/java/org/openmrs/module/emrapi/db/EmrApiDAOImpl.java
> +      String hqlEncounterTypeId = "SELECT et.id FROM EncounterType et WHERE et.uuid = :encounterTypeUuid";
Change this to a join please.

2025-02-20 18:46 UTC, merged

2025-02-20 18:58 UTC, jayasanka-sack commented
cc: @denniskigen @gracepotma